# Generated by Django 3.2.13 on 2022-05-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='face_url',
            new_name='faceUrl',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='open_id',
            new_name='openId',
        ),
    ]
