# Generated by Django 3.2.13 on 2022-05-29 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_course_courseforteacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseForTeacher',
            new_name='CourseForUser',
        ),
    ]
