# Generated by Django 3.2.13 on 2022-06-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20220530_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupSignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(max_length=255, null=True)),
                ('number', models.CharField(max_length=255, null=True)),
                ('section', models.BigIntegerField(null=True)),
                ('time', models.DateTimeField(null=True)),
                ('reason', models.CharField(max_length=255, null=True)),
                ('state', models.BooleanField()),
            ],
        ),
    ]
